
server:
  port: 11004

spring:
  application:
    name: ms-config-server

  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/mulayam/ms-config-repo.git
          clone-on-start: true
          search-paths:
            - uat1
            - uat2


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:11000/eureka/