server:
  port: 11000

spring:
  application:
    name: ms-discovery-server

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:11000/eureka
