server:
  port: 11001
  servlet:
    context-path: /order

spring:
  application:
    name: ms-order-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:11000/eureka/
